version: "3.7"
services:
  proxy:
    build:
      context: ./Proxy
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  user-service:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "3000"
    environment:
      - PROXY_URL=http://proxy:8080/
      - DATABASE_URL=mongodb://app-database:27017/users
    depends_on:
      - proxy
      - app-database

  friendship-service:
    build:
      context: ./FriendshipService
      dockerfile: Dockerfile
    ports:
      - "3001"
    environment:
      - PROXY_URL=http://proxy:8080/
      - DATABASE_URL=mongodb://app-database:27017/friendships
    depends_on:
      - proxy
      - app-database

  transaction-service:
    build:
      context: ./TransactionService
      dockerfile: Dockerfile
    ports:
      - "3002"
    environment:
      - PROXY_URL=http://proxy:8080/
      - DATABASE_URL=mongodb://app-database:27017/transactions
    depends_on:
      - proxy
      - app-database

  card-service:
    build:
      context: ./CardService
      dockerfile: Dockerfile
    ports:
      - "3003"
    environment:
      - PROXY_URL=http://proxy:8080/
      - DATABASE_URL=mongodb://app-database:27017/cards
    depends_on:
      - proxy
      - app-database

  account-service:
    build:
      context: ./AccountService
      dockerfile: Dockerfile
    ports:
      - "3004"
    environment:
      - PROXY_URL=http://proxy:8080/
      - DATABASE_URL=mongodb://app-database:27017/accounts
    depends_on:
      - proxy
      - app-database

  friend-transaction-service:
    build:
      context: ./FriendTransactionService
      dockerfile: Dockerfile
    ports:
      - "3005"
    environment:
      - PROXY_URL=http://proxy:8080/
    depends_on:
      - proxy
      - app-database

  nfc-transaction-service:
    build:
      context: ./NFCTransactionService
      dockerfile: Dockerfile
    ports:
      - "3006"
    environment:
      - PROXY_URL=http://proxy:8080/
    depends_on:
      - proxy
      - app-database

  external-transaction-service:
    build:
      context: ./ExternalTransactionService
      dockerfile: Dockerfile
    ports:
      - "3007"
    environment:
      - PROXY_URL=http://proxy:8080/
      - DATABASE_URL=mongodb://app-database:27017/transactions
      - EXTERNAL_BANK_URL=http://external-bank-service:8081/
    depends_on:
      - proxy
      - app-database

  external-bank-service:
    build:
      context: ./ExternalBank
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  app-database:
    image: mongo:4.4.18
    restart: on-failure
    ports:
      - '27017:27017'
    volumes:
      - app_database:/data/db

volumes:
  app_database:
