name: Build and Run

on:
  workflow_run:
    workflows: ["Build Parser"]
    branches: [main]
    types:
      - completed
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # utile pour lancer le workflow manuellement

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Mise à jour à la dernière version
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies and Build Discovery
        run: |
          cd discovery
          npm install
          npm run build
          npm run exec:windows -- -sn
          cd ..

      - name: Set up JDK 19
        uses: actions/setup-java@v3  # Mise à jour à la dernière version
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Install Graphviz
        run: sudo apt-get install graphviz

      - name: Download Parser JAR
        uses: actions/download-artifact@v3
        with:
          name: jar-artifacts

      - name: Unzip
        run: |
          mv jar-artifacts/*.jar parser.jar

      - name: Run Parser
        run: |
          java -jar parser.jar --inputs=./model --output=./output

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: image-artifacts
          path: |
            output/*.png
            output/*.svg