name: Build Parser

on:
  push:
    paths:
      - 'parser/**'
  workflow_dispatch:

jobs:
  build-parser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v3  # Mise à jour à la dernière version
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Build Parser
        run: |
          cd parser
          mvn clean package

      - name: Upload Jar
        uses: actions/upload-artifact@v3
        with:
          name: jar-artifacts
          path: parser/target/*-dependencies.jar