name: Build and Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # utile pour lancer le workflow manuellement

jobs:
  build-parser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4  # Mise à jour à la dernière version
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build Parser
        run: |
          cd parser
          mvn clean package
          cd target
          rm parser-1.0.jar
          mv *-dependencies.jar parser-1.0.jar

      - name: Upload Jar to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifacts
          path: parser/target/parser-1.0.jar
          retention-days: 1 # Supprime l'artefact après 1 jour

  build-and-run:
    needs: build-parser
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Parser JAR
        uses: actions/download-artifact@v4
        with:
          name: jar-artifacts

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Install Graphviz
        run: sudo apt-get install graphviz

      - name: Install Dependencies and Build Discovery
        run: |
          cd discovery
          npm install
          npm run build
          cd ..

      - name: Run Discovery
        run: |
          cd discovery
          npm run exec:windows -- -sn
          cd ..

      - name: Run Parser
        run: |
          java -jar parser-1.0.jar --inputs=./models --output=./output

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: image-artifacts
          path: |
            output/*.png
            output/*.svg
