name: Build and Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # utile pour lancer le workflow manuellement

jobs:
  build-parser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v3  # Mise à jour à la dernière version
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Build Parser
        run: |
          cd parser
          mvn clean package

      - name: Upload Jar
        uses: actions/upload-artifact@v3
        with:
          name: jar-artifacts
          path: parser/target/*-dependencies.jar
          retention-days: 1

  build-and-run:
    needs: build-parser
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Mise à jour à la dernière version
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies and Build Discovery
        run: |
          cd discovery
          npm install
          npm run build
          npm run exec:windows -- -sn
          cd ..

      - name: Set up JDK 19
        uses: actions/setup-java@v3  # Mise à jour à la dernière version
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Install Graphviz
        run: sudo apt-get install graphviz

      - name: Download Parser JAR
        uses: actions/download-artifact@v3
        with:
          name: jar-artifacts

      - name: Run Parser
        run: |
          java -jar parser-1.0-jar-with-dependencies.jar --inputs=./models --output=./output

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: image-artifacts
          path: |
            output/*.png
            output/*.svg
