name: ContextMapperForward

on:
  push:
    branches:
      - milestone1
  pull_request:
    branches:
      - milestone1
      - main
  workflow_dispatch: # utile pour lancer le workflow manuellement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Mise à jour à la dernière version
      - name: Set up JDK 19
        uses: actions/setup-java@v3  # Mise à jour à la dernière version
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Install Graphviz
        run: sudo apt-get install graphviz

      - name: Build with Maven
        run: mvn -B package --file ./context-mapper-forward/pom.xml

      - name: Run with Maven
        run: mvn -B exec:java --file ./context-mapper-forward/pom.xml

      - uses: actions/upload-artifact@v3  # Mise à jour à la dernière version
        with:
          name: generated-png-files
          path: ./src-gen/*.png
